# RUN: llvm-mc -arch=vectorproc -show-encoding %s | FileCheck %s
# This file auto-generated by make_memory_tests.py
load.u8 s10, 20(s5) ; CHECK: encoding: [0x45,0x15,0x00,0xa0]
load.u8 s11, (s6) ; CHECK: encoding: [0x66,0x01,0x00,0xa0]
load.s8 s10, 20(s5) ; CHECK: encoding: [0x45,0x15,0x00,0xa2]
load.s8 s11, (s6) ; CHECK: encoding: [0x66,0x01,0x00,0xa2]
load.u16 s12, 30(s7) ; CHECK: encoding: [0x87,0x1d,0x00,0xa4]
load.u16 s13, (s8) ; CHECK: encoding: [0xa8,0x01,0x00,0xa4]
load.s16 s12, 30(s7) ; CHECK: encoding: [0x87,0x1d,0x00,0xa6]
load.s16 s13, (s8) ; CHECK: encoding: [0xa8,0x01,0x00,0xa6]
load.32 s14, 40(s9) ; CHECK: encoding: [0xc9,0x29,0x00,0xa8]
load.32 s15, (s10) ; CHECK: encoding: [0xea,0x01,0x00,0xa8]
store.8 s1, 50(s2) ; CHECK: encoding: [0x22,0x30,0x00,0x82]
store.16 s3, 60(s4) ; CHECK: encoding: [0x64,0x3c,0x00,0x86]
store.32 s5, 70(s6) ; CHECK: encoding: [0xa6,0x44,0x00,0x88]

foo: .word bar
	load.32 s4, foo		# CHECK: encoding: [0x9f,0bAAAAAA00,A,0b1010100A]
		# CHECK: fixup A - offset: 0, value: foo, kind: fixup_VectorProc_PCRel_MemAccExt

